In [2]:
import numpy as np

In [2]:
myArray = np.array([1,2,3,4,5])
myList = [1,2,3,4,5]

In [11]:
myArray

array([1, 2, 3, 4, 5])

In [12]:
multiplyList = myList * 5
multiplyArray = myArray * 5

print(multiplyList,multiplyArray)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5] [ 5 10 15 20 25]


In [7]:
myNewArray = np.array(myList)

In [3]:
divArray = myArray / 2
reduceArray = myArray - 2
addArray = myArray + 2
squareArray = myArray ** 2

print('add', addArray)
print('red', reduceArray)
print('square', squareArray)
print('div', divArray)

add [3 4 5 6 7]
red [-1  0  1  2  3]
square [ 1  4  9 16 25]
div [0.5 1.  1.5 2.  2.5]


In [4]:
isMyarrayMoreThan3 = myArray > 3

valueMoreThan3c = myArray[myArray > 3]
print(valueMoreThan3c)

[4 5]


In [5]:
isMyarrayMoreThan3

array([False, False, False,  True,  True])

In [3]:
arrayMulti = np.array([[1,2,3,4],
                       [5,6,7,8],
                       [9,10,11,12]])
print(arrayMulti.shape)

(3, 4)


In [4]:
print(type(arrayMulti))

<class 'numpy.ndarray'>


In [5]:
print(arrayMulti[1,0])
print(arrayMulti[1][0])

5
5


In [8]:
print(arrayMulti[0:,1:3])

[[ 2  3]
 [ 6  7]
 [10 11]]


In [9]:
mystudentData = np.genfromtxt("./data.csv",skip_header=1,delimiter=',',filling_values=40)
mystudentData

array([[70., 75., 80., 30.],
       [75., 80., 90., 68.],
       [65., 77., 60., 90.],
       [40., 60., 55., 75.]])

In [10]:
maxInclass = np.amax(mystudentData, axis = 0)
print(maxInclass)

[75. 80. 90. 90.]


In [11]:
meanStudentTiapMapel = np.mean(mystudentData, axis=1)
print(meanStudentTiapMapel)

[63.75 78.25 73.   57.5 ]


In [12]:
sumStudent = np.sum(mystudentData, axis=1)
sumStudent

array([255., 313., 292., 230.])

In [13]:
minStudent = np.min(mystudentData, axis=1)
minStudent

array([30., 68., 60., 40.])

In [17]:
medianStudent = np.median(mystudentData, axis=1)
medianStudent

array([72.5, 77.5, 71. , 57.5])

In [22]:
maxInclass = np.amax(mystudentData, axis = 0)
meanStudentTiapMapel = np.mean(mystudentData, axis=1)
sumStudent = np.sum(mystudentData, axis=1)
medianStudent = np.median(mystudentData, axis=1)
sortStudent = np.sort(mystudentData, axis=1)
print('max ',maxInclass)
print('mean ',meanStudentTiapMapel)
print('sum ',sumStudent)
print('median ',medianStudent)
print('sort ',sortStudent)

max  [75. 80. 90. 90.]
mean  [63.75 78.25 73.   57.5 ]
sum  [255. 313. 292. 230.]
median  [72.5 77.5 71.  57.5]
sort  [[30. 70. 75. 80.]
 [68. 75. 80. 90.]
 [60. 65. 77. 90.]
 [40. 55. 60. 75.]]


In [18]:
np.lookfor('sort')

Search results for 'sort'
-------------------------
numpy.sort
    Return a sorted copy of an array.
numpy.msort
    Return a copy of an array sorted along the first axis.
numpy.argsort
    Returns the indices that would sort an array.
numpy.lexsort
    Perform an indirect stable sort using a sequence of keys.
numpy.searchsorted
    Find indices where elements should be inserted to maintain order.
numpy.sort_complex
    Sort a complex array using the real part first, then the imaginary part.
numpy.unique
    Find the unique elements of an array.
numpy.ma.sort
    Return a sorted copy of the masked array.
numpy.union1d
    Find the union of two arrays.
numpy.Bytes0.sort
    Scalar method identical to the corresponding array attribute.
numpy.setxor1d
    Find the set exclusive-or of two arrays.
numpy.ma.argsort
    Return an ndarray of indices that sort the array along the
numpy.Bytes0.argsort
    Scalar method identical to the corresponding array attribute.
numpy.intersect1d
    Find th

In [15]:
[y, x] = mystudentData.shape
mystudentData[2:y,3:x]

array([[90.],
       [75.]])

In [28]:
mystudentData = np.append(mystudentData, [[45],[50],[40],[90]], axis=1)

In [33]:
newReshape = np.reshape(mystudentData,(10,2))
newResize = np.resize(mystudentData,(5,4))
print('normal\n',mystudentData)
print('Reshape\n',newReshape)
print('Resize\n',newResize)

normal
 [[70. 75. 80. 30. 45.]
 [75. 80. 90. 68. 50.]
 [65. 77. 60. 90. 40.]
 [40. 60. 55. 75. 90.]]
Reshape
 [[70. 75.]
 [80. 30.]
 [45. 75.]
 [80. 90.]
 [68. 50.]
 [65. 77.]
 [60. 90.]
 [40. 40.]
 [60. 55.]
 [75. 90.]]
Resize
 [[70. 75. 80. 30.]
 [45. 75. 80. 90.]
 [68. 50. 65. 77.]
 [60. 90. 40. 40.]
 [60. 55. 75. 90.]]
